set_false_path -from * -to [get_ports hps_io_hps_io_emac0_inst_TX_CLK]
set_false_path -from * -to [get_ports hps_io_hps_io_emac0_inst_TXD0]
set_false_path -from * -to [get_ports hps_io_hps_io_emac0_inst_TXD1]
set_false_path -from * -to [get_ports hps_io_hps_io_emac0_inst_TXD2]
set_false_path -from * -to [get_ports hps_io_hps_io_emac0_inst_TXD3]
set_false_path -from [get_ports hps_io_hps_io_emac0_inst_RXD0] -to *
set_false_path -from [get_ports hps_io_hps_io_emac0_inst_MDIO] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_emac0_inst_MDIO]
set_false_path -from * -to [get_ports hps_io_hps_io_emac0_inst_MDC]
set_false_path -from [get_ports hps_io_hps_io_emac0_inst_RX_CTL] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_emac0_inst_TX_CTL]
set_false_path -from [get_ports hps_io_hps_io_emac0_inst_RX_CLK] -to *
set_false_path -from [get_ports hps_io_hps_io_emac0_inst_RXD1] -to *
set_false_path -from [get_ports hps_io_hps_io_emac0_inst_RXD2] -to *
set_false_path -from [get_ports hps_io_hps_io_emac0_inst_RXD3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_SS3]
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_SS2]
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_SS1]
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO0]
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO1]
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO2]
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO3]
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_SS0]
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_CLK]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_CMD] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CMD]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D0]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D1]
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CLK]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D2]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D3]
set_false_path -from [get_ports hps_io_hps_io_spis0_inst_CLK] -to *
set_false_path -from [get_ports hps_io_hps_io_spis0_inst_MOSI] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_spis0_inst_MISO]
set_false_path -from [get_ports hps_io_hps_io_spis0_inst_SS0] -to *
set_false_path -from [get_ports hps_io_hps_io_uart0_inst_RX] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_uart0_inst_TX]
set_false_path -from [get_ports hps_io_hps_io_uart0_inst_CTS] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_uart0_inst_RTS]
set_false_path -from [get_ports hps_io_hps_io_i2c0_inst_SDA] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_i2c0_inst_SDA]
set_false_path -from [get_ports hps_io_hps_io_i2c0_inst_SCL] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_i2c0_inst_SCL]
set_false_path -from [get_ports hps_io_hps_io_i2c3_inst_SDA] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_i2c3_inst_SDA]
set_false_path -from [get_ports hps_io_hps_io_i2c3_inst_SCL] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_i2c3_inst_SCL]